version: "3.7"
services: 
  nwlserver:
    build:
      dockerfile: dockerfile
      context: .
    image: "juzcare/dev"
    ports:
      - "6003:4000"
    volumes:
      - "./build:/juzcare-backend/dev/build"
  
  mongodb:
    image: bitnami/mongodb:4.4-debian-10
    ports:
      - "27020:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local