version: "3.9"
services: 
  nwlserver:
    build:
      dockerfile: dockerfile
      context: .
    image: "juzcare/dev"
    ports:
      - "6003:3006"
    volumes:
      - "./build:/juzcare-backend/dev/build"